### ISSUE TITLE
Reload the application without having to close it

### ISSUE THREAD

**Issue by ivanalaman** [daattali/shinyjs#216] opened 2020-09-17 17:00 UTC
Dear, good afternoon!

I'm trying to use a set of commands like for example
jscode <- "brilliantjs.refresh = function () {location.reload ();}"

In order to update ALL my app after an action, more is not working. Only one tabPanel is being updated. The update involves creating new buttons in some menus. This is done, but you need to close the app and restart for the changes to take effect. I wish the user didn't have to do that. The application is available at https://github.com/ivanalaman/EDM. In the second menu "CREATE/REMOVE DATABASE EXAMS" when creating a database for you, new buttons are created. If you can give me a light I would appreciate it. I have tirelessly sought a solution and found none.
Thank you.

**Comment by daattali** [comment] 2020-09-17 17:06
You can try using the `shinyjs::reset()` function or the new function `shinyjs::refresh()`, perhaps one of those will help you. Other than that I can't provide much help, as this is not a bug in shinyjs I'm going to close this issue. If you're looking for individual help, feel free to [contact me through my consulting service](https://attalitech.com)

**Closed by daattali** 2020-09-17 17:06 UTC
