### ISSUE TITLE
Some shinyjs functions not working in shiny module

### ISSUE THREAD

**Issue by Yang-Tang** [daattali/shinyjs#50] opened 2016-01-08 08:16 UTC
The `show`, `hide`, `enable`, `disable` and `reset` functions are not working in shiny module.
I used the following code with shiny v0.12.2.9009 and shinyjs v0.3.1:

```
library(shiny)
library(shinyjs)

moduleTestUI <- function('id'){
  
  ns <- NS(id)
  
  tagList(
    
    disabled(div(
      
      id=ns('the_div'),
      
      textInput(ns('text'), 'text input'),
      selectInput(ns('select'), 'select input', letters[1:5]),
      checkboxInput(ns('checkbox'), 'checkbox'),
      radioButtons(ns('radio'), 'radiobuttons', LETTERS[1:5], inline=T),
      sliderInput(ns('slider'), 'slider', 1, 5, 1),
      actionButton(ns('button'), 'button')
      
    )),
    
    hr(),
    
    actionButton(ns('show'), 'Show'),
    actionButton(ns('hide'), 'Hide'),
    actionButton(ns('enable'), 'Enable'),
    actionButton(ns('disable'), 'Disable'),
    actionButton(ns('reset'), 'Reset')
    
  )
}

moduleTest <- function(input, output, session){
  
  onclick('show', show('the_div'))
  onclick('hide', hide('the_div'))
  onclick('enable', enable('the_div'))
  onclick('disable', disable('the_div'))
  onclick('reset', reset('the_div'))
  
}

server <- function(input, output) {
  
  callModule(moduleTest, 'test')

}

ui <- fluidPage(
  
  useShinyjs(),
  
  moduleTestUI('test')

)

shinyApp(ui, server)
```

**Comment by daattali** [comment] 2016-01-08 17:14
I don't know how modules work, I'll look into it when I have some time and hopefully it'll be easy to make shinyjs work with them

**Comment by daattali** [comment] 2016-01-08 17:27
After a quick look at the code, it makes complete sense to me why the code doesn't work. By using a module, the id of the show button is not `show`, but `test-show`. And the id for `the_div` is `test-the_div`. The above code tells shinyjs to try to operate on the wrong ids. I'm not familiar with the modules syntax of `callModule()` so I don't know what the correct fix is, but at least it makes sense that it doesn't work like that

**Comment by daattali** [comment] 2016-01-08 18:17
(Just dumping my thoughts here)

I think there are two main problems with shinyjs working inside modules.

1. Inside a module server function, `getDefaultReactiveDomain()` returns a `session_proxy` object instead of the real `session` object, and all shinyjs functions rely on having access to the session. [Code](https://github.com/daattali/shinyjs/blob/master/R/utils.R#L7-L22). @jcheng5 - is there a way to ensure I get the shiny app's global `session` object? If I use `getDefaultReactiveDomain()` and get a `session_proxy` value, is it safe to call `session[['parent']]`?

2. If I do implement the (hacky?) solution above, then the module server code still won't work because shinyjs functions have no way to know that string "foo" should really be inside a namespace. I'm not sure how to approach that.

**Comment by jcheng5** [comment] 2016-01-08 21:24
1. You don't want the global object, you actually want the proxy. The proxy should support all the same operations; if not, it's a bug, and you should definitely let me know. (ASAP, please--we're planning to go to CRAN next week!)

2. Something like this:

```
show <- function(id, condition = NULL, ignoreNamespace = FALSE) {
  sess <- getSession()
  if (!ignoreNamespace) {
    id <- sess$ns(id)
  }

  sess$sendCustomMessage(...)
}
```

`sess$ns` will just pass the value straight through if you're not in a module.

**Comment by daattali** [comment] 2016-01-08 21:37
Thanks Joe. 

1. When I used the global session object, it worked. Using the proxy session did not. I haven't debugged yet to see where exactly the problem occurs, I can try that later and report back. It's entirely possible I'm doing something funky and it's my fault it isn't working

2. Something like that could probably work, but I was hoping for a general solution that would just work both for modules and for regular apps. Also, part of the elegance of these shinyjs functions is that R doesn't intercept the arguments to see what arguments were passed or do any work, it just passes them straight along to the JS layer, and this solution wouldn't allow that

I'm about to leave to Seattle for the weekend so might not have time to look into this until next week, not sure what your CRAN deadlines are

**Comment by jcheng5** [comment] 2016-01-08 22:59
The function I wrote was intended to work for both modules and regular apps. `session$ns` is supported on both, it just doesn't do anything in a regular app.

The way these shinyjs functions are written right now, all the benefit of that elegance is accrued to you, the implementer, not the users. The signature for all of these functions are `function(...)`, when the JS functions on the other side are expecting specific arguments; this is a big disadvantage in usability, especially when using RStudio or other IDEs that show usage hints and support argument autocompletion. It also means that argument name misspellings are not caught at the point they're committed. And finally, the particular implementation you've used for `jsFunc` means that `do.call(shinyjs::show, args)` doesn't work (certainly that's an edge case, but surprising nonetheless). So I think there are other good reasons for adding a thin layer of code for each function.

That said, obviously, it's your project, and nobody is going to fault you for making whatever tradeoffs you feel like. If you value conciseness of implementation above these other considerations (and let's face it, metaprogramming is just fun), that's your prerogative. So just take the above as my two cents.

**Comment by daattali** [comment] 2016-01-08 23:42
@jcheng5 after reading your opinion, I think you're 100% right. This
package started off as a tiny fun pet project and I enjoyed the meta
programming as a cool exercise, but I haven't reevaluated the
implementation since. Your points do make a lot of sense, I should refactor
the code to address the issues you mentioned. This will also make
integrating with shiny modules easier. Thank you for the very helpful
cents. And I'll let you know if I find something wrong with proxy session,
but it's likely a problem on my end.

Yang-Tang thanks for bringing this to my attention. If you're interested in
a quick dirty fix, most shinyjs functions should work if you change
'show("text")'  to 'show(session$ns("text"))'. I don't think
reset,onclick,delay will work.

**Comment by daattali** [comment] 2016-01-09 17:35
@jcheng5 just reporting back that session proxy does indeed work just fine.

If anyone's curious, the problem I was getting is because there is [code like this](https://github.com/daattali/shinyjs/blob/a0174adb7d798920e8f59cd0a818b15649b6679a/R/delay.R#L46-L54) that gives JavaScript an HTML id to use as an input, but that id now needs to be namespaced.

**Closed** 2016-01-17 01:16 UTC

**Comment by daattali** [comment] 2016-01-17 01:21
@Yang-Tang can you download the latest shinyjs from github and try now?  Modules should be supported now, I'd appreciate your testing too to see if it works for your usecase

Here's a basic app that tries to use many different shinyjs functions inside a module for testing purposes:

```
library(shiny)
library(shinyjs)

moduleTestUI <- function(id){

  ns <- NS(id)

  tagList(
    h1("Tests to ensure shinyjs works in Shiny modules"),
    br(),
    h4("Clicking on the Name text input will show an alert box after 1 second"),
    div(id = ns('form'),
      textInput(ns('text'), 'Name', value = "Dean"),
      colourInput(ns('col'), 'Colour', value = "blue"),

      actionButton(ns("resetForm"), "Reset form"),
      actionButton(ns("resetText"), "Reset text"),
      actionButton(ns("hideForm"), "Hide form"),
      actionButton(ns("toggleText"), "Toggle text"),
      actionButton(ns("disableText"), "Disable text")
    )
  )
}


moduleTest <- function(input, output, session) {
  onclick("text", delay(1000, info("clicked me!")))
  onevent("mouseenter", "text", logjs("entered"))

  observeEvent(input$resetForm, reset("form"))
  observeEvent(input$resetText, reset("text"))
  observeEvent(input$hideForm, hide("form"))
  observeEvent(input$toggleText, toggle("text", anim = TRUE))
  observeEvent(input$disableText, disable("text"))
}


ui <- fluidPage(
  useShinyjs(debug = TRUE),
  moduleTestUI('test')
)
server <- function(input, output, session) {
  callModule(moduleTest, 'test')
}
shinyApp(ui = ui, server = server)
```

**Comment by Yang-Tang** [comment] 2016-01-18 03:12
@daattali I'm really appreciate your quick response and bug fixing. The lastest shinyjs works very well in my case. Thank you again!

**Comment by shrektan** [comment] 2016-01-18 04:04
Works for me too.  Thanks!


发自网易邮箱大师
在2016年01月18日 11:12，Yang-Tang 写道:

@daattali I'm really appreciate your quick response and bug fixing. The lastest shinyjs works very well in my case. Thank you again!

**Comment by pczhang** [comment] 2019-05-12 14:32
I couldn't make the above example given by @Yang-Tang to work in a markdown file. Would you please what I did wrong here?

---
title: "Test"
output: html_document
runtime: shiny
---

```{r, include = F}
library(shiny)
library(shinyjs)
useShinyjs(rmd = TRUE)

moduleTestUI <- function(id){

  ns <- NS(id)

  tagList(

    disabled(div(

      id=ns('the_div'),

      textInput(ns('text'), 'text input'),
      selectInput(ns('select'), 'select input', letters[1:5]),
      checkboxInput(ns('checkbox'), 'checkbox'),
      radioButtons(ns('radio'), 'radiobuttons', LETTERS[1:5], inline=T),
      sliderInput(ns('slider'), 'slider', 1, 5, 1),
      actionButton(ns('button'), 'button')

    )),

    hr(),

    actionButton(ns('show'), 'Show'),
    actionButton(ns('hide'), 'Hide'),
    actionButton(ns('enable'), 'Enable'),
    actionButton(ns('disable'), 'Disable'),
    actionButton(ns('reset'), 'Reset')

  )
}

moduleTest <- function(input, output, session){

  onclick('show', show('the_div'))
  onclick('hide', hide('the_div'))
  onclick('enable', enable('the_div'))
  onclick('disable', disable('the_div'))
  onclick('reset', reset('the_div'))

}

callModule(moduleTest, 'test')
```

```{r}
moduleTestUI('test')
```

**Comment by daattali** [comment] 2019-05-12 16:17
It's possible that shinyjs doesn't work in modules inside rmarkdown. I've
never tried, but if it doesn't work I'm not sure I would prioritize fixing
it, because I generally view an app that's complex enough to use modules as
being a full shiny app, not an rmd

**Comment by pczhang** [comment] 2019-05-12 16:30
ok. I need to use rmd to generate interactive documents to communicate with my collaborators. Modules are so convenient to re-use codes since I can just pack it to my personal package and call it from time to time. Will try to look for other solutions then. thanks anyway.

**Comment by daattali** [comment] 2019-05-12 17:50
@pczhang I just tried copying the example from the top of this page into an RMD file and it did work for me. So I don't think there's any issues with shinyjs in modules in rmd.

**Comment by pczhang** [comment] 2019-05-12 21:35
thanks! When you said "the example from the top of this page", did you mean the example given by Yang-Tang based on shinyApp?

Or you meant the example given by me, which is similar to the document from your website? So you just put the elements directly in rmd. Thanks.

```{r}
library(shinyjs)
useShinyjs(rmd = TRUE)
actionButton("button", "Click me")
div(id = "hello", "Hello!")
observeEvent(input$button, {
 toggle("hello")
})
```

**Comment by daattali** [comment] 2019-05-12 23:47
Sorry the code I tried running was actually the code from my own comment
above: https://github.com/daattali/shinyjs/issues/50#issuecomment-172282295

I put that in an rmd and it works

**Comment by pczhang** [comment] 2019-05-16 01:54
If you took "useShinyjs(debug = TRUE)" out from fluidPage but put it globally, does it still work? In my testing, it didn't even with "rmd = TRUE".

```{r}
library(shinyjs)
useShinyjs(rmd = TRUE)

testUI <- function(id) {
    ns <- NS(id)
    tagList(
        actionButton(ns("button"), "Click me"),
        div(id = ns("hello"), paste0("Hello, ", id, "!"))
    )
}

test <- function(input, output, session) {
    observeEvent(input$button, {
        toggle("hello")
    })
}

ui <- fluidPage(
  testUI('world')
)
server <- function(input, output, session) {
  callModule(test, 'world')
}
shinyApp(ui = ui, server = server)
```

**Comment by daattali** [comment] 2019-05-16 04:36
It shouldn't work. `rmd=TRUE` is for when you're using it in an RMD.

**Comment by pczhang** [comment] 2019-05-16 12:06
I meant that if you put the code in the RMD it still doesn't work even 
with rmd=TRUE.

only if you put useShinyjs inside fluidPage, it will work and you don't 
need rmd=TRUE at all.

**Comment by daattali** [comment] 2019-05-16 15:02
That entire code is code for a proper embedded shiny app. Usermd works if
you're using shiny inputs inside an rmd file (if you're calling the
shinyApp function and defining ui and server, that's a proper shiny app)
