### ISSUE TITLE
shinyjs not loading in module nested in renderUI

### ISSUE THREAD

**Issue by yonicd** [daattali/shinyjs#136] opened 2017-06-30 03:06 UTC
i have a module that uses shinyjs. when i have the module in a renderUI the shinyjs stops responding

```r
observeEvent(,{
  output$a<-renderUI({
    moduleUI
  })
})
```

This is the working example. It should hide the checkbox group UI `(checkbox.show = FALSE)`

```r
devtools::intall_github('yonicd/regexSelect')
library(shiny)
library(regexSelect)

ui <- shiny::fluidPage(
  selectInput('sel','select data',c('a','b'),selected = 'a'),
  shiny::uiOutput('rs'),
  shiny::tableOutput("data")
)

server <- function(input, output, session) {
  
  observeEvent(input$sel,{
    output$rs<-renderUI({
      regexSelectUI(id = "a", label = "Variable:",choices = names(iris),
                              checkbox.show = FALSE)
    })
  })
  
  curr_cols<-callModule(regexSelect, "a",shiny::reactive(names(iris)))
  
  observeEvent(curr_cols(),{
    cols_now<-curr_cols()
    if(length(cols_now)==0)  cols_now<-names(iris)
    output$data <- shiny::renderTable({iris[,cols_now , drop = FALSE]}, rownames = TRUE)
  })
}

shiny::shinyApp(ui, server)
```

**Comment by daattali** [comment] 2017-06-30 12:00
It's not super clear what you're trying to do and what should happen. Can you try to post a minimal example (without external dependencies)

**Comment by yonicd** [comment] 2017-06-30 12:39
this is a module taken from rstudio, adding shinyjs to it and controlling if id='quote' is shown.

```r
# Module UI function
csvFileInput <- function(id, label = "CSV file",showme=TRUE) {
  # Create a namespace function using the provided id
  ns <- NS(id)
  
  tagList(
    switch(as.numeric(showme==TRUE)+1,shinyjs::useShinyjs(),list()),
    fileInput(ns("file"), label),
    checkboxInput(ns("heading"), "Has heading"),
    selectInput(ns("quote"), "Quote", c(
      "None" = "",
      "Double quote" = "\"",
      "Single quote" = "'"
    ))
  )
}

# Module server function
csvFile <- function(input, output, session, stringsAsFactors) {
  
  shinyjs::hide(id = 'quote')
  
  # The selected file, if any
  userFile <- reactive({
    # If no file is selected, don't do anything
    validate(need(input$file, message = FALSE))
    input$file
  })
  
  # The user's data, parsed into a data frame
  dataframe <- reactive({
    read.csv(userFile()$datapath,
             header = input$heading,
             quote = input$quote,
             stringsAsFactors = stringsAsFactors)
  })
  
  # We can run observers in here if we want to
  observe({
    msg <- sprintf("File %s was uploaded", userFile()$name)
    cat(msg, "\n")
  })
  
  # Return the reactive that yields the data frame
  return(dataframe)
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      csvFileInput("datafile", "User data (.csv format)",showme = TRUE)
    ),
    mainPanel(
      dataTableOutput("table")
    )
  )
)

server <- function(input, output, session) {
   datafile <- callModule(csvFile, "datafile",
                         stringsAsFactors = FALSE)
  
  output$table <- renderDataTable({
    datafile()
  })
}

shinyApp(ui, server)
```

if i change the call to the module by nesting it in a renderUI, shinyjs is ignored

```r
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      shiny::uiOutput('csv'),
    ),
    mainPanel(
      dataTableOutput("table")
    )
  )
)

server <- function(input, output, session) {
  
  
    output$csv<-renderUI({
      csvFileInput("datafile", "User data (.csv format)",showme = FALSE)   
    })    
  
  
  
  datafile <- callModule(csvFile, "datafile",
                         stringsAsFactors = FALSE)
  
  output$table <- renderDataTable({
    datafile()
  })
}

shinyApp(ui, server)
```

**Comment by daattali** [comment] 2017-06-30 14:07
Thanks, I think I see the problem.

In the second example, I believe the module server function (callModule) is
called before the UI portion of the module is rendered. So it's not a bug,
it's just the correct order of things that are called. Does that make sense?

I'm traveling and not able to take a very deep look at the moment but I'm
pretty sure that's what you're seeing.

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by yonicd** [comment] 2017-06-30 15:37
that's what i thought also , but just wanted to make sure. so basically the useshinyjs isnt being called on time? or is not registering the correct session?

**Comment by daattali** [comment] 2017-06-30 15:51
I think the hide function is being called too early. You can put some
debugging print statements there to see the order of execution

**Comment by yonicd** [comment] 2017-06-30 15:55
when you get a chance,  is there another way of achieving the same goal. the input that is attached to that UI needs to be available as an input for the module server, but the user has the option of hiding it from the module UI. 

conditional panel doesnt seem to fit since it is looking for a js object and in this case it is a formal of the UI function. 

and an if statement directly on the UI that is showing/hiding is also a problem since it is not created when show=FALSE and then is missing for the server side.

**Comment by daattali** [comment] 2017-07-03 12:53
If you're trying to get something to hide as soon as it renders, then maybe
use the shinyjs::hidden() function (in the UI) instead of hide() in the
server? Often when I saw people complain about this "bug", this solution
worked for them. I'm closing the issue since it's not a bug. See you at
useR!

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Closed** 2017-07-03 12:53 UTC

**Comment by yonicd** [comment] 2017-07-03 15:23
that works. thanks

**Comment by yonicd** [comment] 2017-07-03 15:24
is there an example of this nuance in the examples you have on the site? that could be a good one to add
