### ISSUE TITLE
Importing Exports within extendShinyjs in Shiny Server

### ISSUE THREAD

**Issue by masato-yoshihara** [daattali/shinyjs#203] opened 2020-03-09 17:40 UTC
I'm using MongoDB Stitch within my Shiny application, and to use my query function, I need to import the Stitch export from the MongoDB Stitch JavaScript SDK. The following is parsed with no issues locally using extendShinyjs:

```
library(shiny)
library(shinyjs)

jsCode <- '
shinyjs.init = function() {
  const {
  Stitch
  } = stitch;

  window.stitchClient = Stitch.initializeDefaultAppClient("xxx");
}'

shinyApp(
  ui = fluidPage(
    tags$head(HTML('<script src="https://s3.amazonaws.com/stitch-sdks/js/bundles/4.9.0/stitch.js"></script>')),
    useShinyjs(),
    extendShinyjs(text = jsCode)
 ),
  server = function(input, output) {
  }
)
```

However, I get the following error when the above code is called by extendShinyjs in the shiny server: **shinyjs: Error parsing the JavaScript code provided**. I've confirmed through repeated tests that the issue is through my calling the Stitch export with the first command of the shinyjs.init function. Not sure if there's a work around this. Thanks for your help!

**Comment by daattali** [comment] 2020-03-10 05:59
Strange, I can't reproduce. An error in parsing, especially with this not-super-standard syntax, is maybe because of the V8 engine. Maybe your server is on a very old version of V8?

**Comment by masato-yoshihara** [comment] 2020-03-10 15:47
Hi Dean, thanks for the response. I'm currently using version 3.0.1 of V8 on R Studio with the V8 engine downloaded using libv8-3.14-dev on Ubuntu. Locally, I'm using version 3.0.1 of V8 on R Studio with the V8 engine downloaded using v8-315 on Homebrew (OSX). I'm not sure what difference this makes.

**Comment by daattali** [comment] 2020-03-10 15:52
Is that the version you had installed already before, or did you just install it?

**Comment by masato-yoshihara** [comment] 2020-03-10 15:57
That's the one I've been running, and I'm still getting the same errors.

Oddly enough, when I run `ct <- v8()` then `cat(ct$eval('const {Stitch} = stitch;'))` on R in the server console, the only error I get is **ReferenceError: stitch is not defined**. So it seems like I only get the parsing error when I run the Shiny app.

**Comment by daattali** [comment] 2020-03-10 16:43
Sounds like your shiny app isn't using the same library. I don't know the setup of your server but you need to make sure to install V8 for the user that runs shiny server (which is by default the `shiny` user). Coincidentally I do have a written resource that may help you with that https://deanattali.com/2015/05/09/setup-rstudio-shiny-server-digital-ocean/#user-libraries
 
This doesn't seem like a shinyjs issue so I'm closing this issue.

**Closed by daattali** 2020-03-10 16:43 UTC

**Comment by masato-yoshihara** [comment] 2020-03-11 16:01
Thanks Dean! For reference, I was running the shiny-server on a container utilizing the rocker/shiny base image, which as of now, uses a Debian 9 (stretch) base image. According to Jeroen (https://github.com/jeroen/V8/issues/86), the V8 parser that came with Debian 9 is the legacy version and consequently, modern JS was not parsed correctly when I was running the script above. rocker/r-ver now uses Debian 10 (buster), so I used that base image, installed dependencies outlined in the rocker/shiny Dockerfile, and the script runs without a problem. Hopefully the rocker/shiny Dockerfile is updated soon!

**Comment by daattali** [comment] 2020-03-11 16:24
Ah good to know!
