### ISSUE TITLE
show sets focus on element

### ISSUE THREAD

**Issue by thothal** [daattali/shinyjs#148] opened 2017-12-07 16:22 UTC
### Problem
I am using a `shinydashboard` design, where I want to hide/show a menu item. This works in principle, but when I `show` the element the focus is set to the corresponding `tabItem` which is an unwanted behavior. Is this an intended behavior? My workaround of adding `updateTabItems(session, "tabs", "item1")`  works but generates a flickering. Any better ideas?

### Reprex
    library(shiny)
    library(shinyjs)
    library(shinydashboard)

    ui <- dashboardPage(
       dashboardHeader(title = "Dashboard"),
       dashboardSidebar(
          sidebarMenu(id = "tabs",
                      menuItem("Item 1", tabName = "item1"),
                      menuItem("Item 2", tabName = "item2")
          ),
          checkboxInput("foo", "Show Item2", TRUE)
       ),
       dashboardBody(
          useShinyjs(),
          tabItems(
             tabItem("item1", h1("Item 1")),
             tabItem("item2", h1("Item 2"))
          )
       )
    )

    server <- function(input, output) {
        observe({
          toggle(condition = input$foo, selector = "a[data-value=item2]")
        })
    }

    runApp(shinyApp(ui = ui, server = server))

**Comment by daattali** [comment] 2017-12-07 17:28
Either I'm not understanding what you're describing, or it's not happening to me.  I tried your code, and the tab never changes

https://imgur.com/a/gvMp4

**Comment by thothal** [comment] 2017-12-08 10:13
I tried it with both IE11 and Chrome. I made a little video showing what is happening on my machine. Any other info you would need me to provide to track down this issue?

[Shiny_Dashboard_IE.zip](https://github.com/daattali/shinyjs/files/1542255/Shiny_Dashboard_IE.zip)

**Comment by daattali** [comment] 2017-12-08 17:57
That is strange. I'm sorry I can't think of any reason why this is
happening. I suppose the first place to start looking at debugging is by
looking at the javascript console to see if anything is happening there,
and to look at the HTML page DOM to see if something strange is happening
there as well, but I don't really know what I'd be looking for. I'm also
working on a fewworkshops this month and am very behind on client projects
so I don't have time to look into this. Very strange though, I'm sorry, no
idea!

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

Attend my 4-day workshop: Learn how to analyze data with R and create Shiny
apps. 15% discount to existing clients. Register here!
<https://www.eventbrite.com/e/modern-r-data-processing-visualization-and-reporting-with-r-tickets-39862492789?aff=deanemail>

**Comment by thothal** [comment] 2017-12-08 22:41
Just for the record, tried it @home as well with Safari, same story. Just because I am curious, which browser were you using?

**Comment by daattali** [comment] 2017-12-09 01:38
Chrome on windows 7. Perhaps its the package versions? @oganm you mind
trying out the code above and see if you see the problem, if you have a few
minutes? Sorry to summon you out of nowhere...

**Comment by oganm** [comment] 2017-12-09 01:56
t'is fine. What package versions do you need? and do you need windows or ubuntu?

**Comment by daattali** [comment] 2017-12-09 02:22
Any and any. Just wondering if anyone can reproduce

**Comment by oganm** [comment] 2017-12-09 02:36
Happens to me too. Everything except R itself is updated to latest version (3.3.2)

**Comment by daattali** [comment] 2017-12-09 04:19
Interesting. When i get my hands on another computer I'll try looking into
it a bit. Thanks for reporting

**Comment by calligross** [comment] 2018-01-05 12:04
+1

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin17.3.0 (64-bit)
Running under: macOS High Sierra 10.13.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.2.20/lib/libopenblasp-r0.2.20.dylib

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ESCBhelper_0.1.0     writexl_0.2          ggrepel_0.7.0        scales_0.5.0         ggplot2_2.2.1        dplyr_0.7.4         
 [7] shinydashboard_0.6.1 shinyjs_0.9.1        shiny_1.0.5          bindrcpp_0.2        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14     lubridate_1.7.1  tidyr_0.7.2      assertthat_0.2.0 digest_0.6.13    utf8_1.1.2       V8_1.5           mime_0.5        
 [9] R6_2.2.2         cellranger_1.1.0 plyr_1.8.4       httr_1.3.1       pillar_1.0.1     rlang_0.1.6      lazyeval_0.2.1   curl_3.1        
[17] bcrypt_1.0       readxl_1.0.0     rstudioapi_0.7   miniUI_0.1.1     DT_0.2           labeling_0.3     stringr_1.2.0    htmlwidgets_0.9 
[25] munsell_0.4.3    compiler_3.4.3   httpuv_1.3.5     pkgconfig_2.0.1  htmltools_0.3.6  openssl_0.9.9    tibble_1.4.1     crayon_1.3.4    
[33] grid_3.4.3       jsonlite_1.5     xtable_1.8-2     gtable_0.2.0     magrittr_1.5     cli_1.0.0        stringi_1.1.6    reshape2_1.4.3  
[41] xml2_1.1.1       tools_3.4.3      glue_1.2.0       markdown_0.8     purrr_0.2.4      yaml_2.1.16      colorspace_1.3-2 rvest_0.3.2     
[49] bindr_0.1

**Comment by daattali** [comment] 2018-01-07 23:31
Sorry other laptops I checked don't exhibit this behaviour. I'm really out of ideas, if anyone who can reproduce the behaviour can try to debug, I'd appreciate that

**Comment by daattali** [comment] 2018-03-28 20:25
I was able to reproduce this now. I believe it's a shiny bug (not shinyjs), because after debugging I noticed that the JS call that actually shows the tab is ok, but then calling `.trigger("shown")` on the tab in order to inform shiny that the tab is shown caused it to get selected. I will file a report with shiny

**Comment by daattali** [comment] 2018-03-28 20:39
This issue will be solved automatically when https://github.com/rstudio/shiny/issues/1991 is solved so I'm closing it as it's not a shinyjs issue

**Closed by daattali** 2018-03-28 20:39 UTC
Labels: help wanted
