### ISSUE TITLE
Strange behavior of print() when used with non-standard types with library(js)

### ISSUE THREAD

**Issue by VermillionAzure** [daattali/shinyjs#41] opened 2015-10-31 08:21 UTC
![shinyjs_error](https://cloud.githubusercontent.com/assets/844699/10862626/158a1f86-7f54-11e5-8e8f-2c8addabb094.png)

There's some sort of strange error with `shinyjs` and `print()` where if I try to print an S4 class, it doesn't print, and instead gives:

    Error: shinyjs: could not find the Shiny session object. This usually happens when a shinyjs function is called from a context that wasn't set up by a Shiny session.

But, `print()` isn't a `shinyjs` function. Even if I use `base::print(the_object)` it still gives the same error.

However, when I `detach('package:shinyjs')`, `print()` starts to work for the classes again. When I `library(shinyjs)` again, it fails.

#### Context

The package in focus from which the class comes from is [Biocondcutor's `clusterProfiler`](http://bioconductor.org/packages/release/bioc/html/clusterProfiler.html) package. It focuses on performing statistical analysis. The final object output is of class `enrichresult` for the class that is in the picture above; a tutorial to produce a similar object using their process is provided on Bioconductor [here](http://bioconductor.org/packages/release/bioc/vignettes/clusterProfiler/inst/doc/clusterProfiler.html#gene-ontology-analysis).

I am using Shiny in conjunction with both `shinyjs` and `clusterProfiler` such that I want to print the little blurb that the object prints out should I do `print(enrichObject_instance)` where `enrichObject_instance` is an object of type `enrichObject`:

    503 human Genes to  MF  test for over-representation. 
 with p value < 0.05 

...or something similar. What I want to do is to capture the output of the print to display in Shiny:

`capture.output(print(enrichObject_instance))`

However, when I display the test in Shiny, nothing shows up. Shiny doesn't crash as well; it simply keeps going on. The state of the object is valid as well; I'm able to display the contents of the `enrichResult` class as a data frame. 

Is there something obvious I'm missing? Or is there something deeper?

**Comment by daattali** [comment] 2015-10-31 09:46
I think this is the same issue as #15 , could you take a look at that closed issue and tell me if you agree? If you follow the comments in that thread, you'll see that this behaviour is supposed to be fixed in R 3.3.0, is your version older than that?

PS. I'm glad to know that at least my decision to include the string "shinyjs" in all my error messages seems to be helpful. Too many packages throw errors without telling you what package failed :)

**Comment by VermillionAzure** [comment] 2015-10-31 20:34
Ah, it seems that my R distribution is on 3.2.2. It's kind of a shame though.

**Comment by daattali** [comment] 2015-10-31 20:38
Yeah... it's not really a bug in shinyjs though. It's just an unfortunate effect of how S4 worked.  There were many similar bugs in many packages, that's why it was fixed in R3.3.0, but yeah it's annoying. Closing this issue, feel free to reopen if you think the problem is not the one described in above

**Closed by daattali** 2015-10-31 20:38 UTC

**Comment by englianhu** [comment] 2017-10-15 10:07
I faced same issue...
```{r}
library('arules')
library('arulesViz')
library('visNetwork')
library('igraph')
detach('package:shinyjs')
source('./function/readfirmData.R')
source('./function/arrfirmData.R')

## Read the data
## Refer to **Testing efficiency of coding.Rmd** at chunk `get-data-summary-table-2.1`
years <- seq(2011, 2015)

## Here I take the majority leagues setting profile which are "league-10-12"
## fMYPriceB = Back with vigorish price; fMYPriceL = Lay with vigorish price
## Here we term as Fair Odds
lProfile <- c(AH = 0.10, OU = 0.12)

mbase <- suppressAll(readfirmData(years = years, pth = './data/') %>% arrfirmData(lProfile = lProfile))
mbase <- mbase$datasets

mbase <- mbase %>% unite(matchID, Home, Away, sep ='.') %>% unite(matchID, DateUK, matchID, sep ='.') %>% dplyr::select(matchID, Selection)

## https://stackoverflow.com/questions/44618956/convert-r-data-frame-column-to-arules-transactions?answertab=votes#tab-top
items <- strsplit(as.character(mbase$Selection), ', ')
trans3 <- as(items, 'transactions')

rules <- apriori(trans3, parameter = list(sup = 0.001, conf = 0.5, target = 'rules', minlen = 1))
Apriori

Parameter specification:
 confidence minval smax arem  aval originalSupport maxtime
        0.5    0.1    1 none FALSE            TRUE       5
 support minlen maxlen target   ext
   0.001      1     10  rules FALSE

Algorithmic control:
 filter tree heap memopt load sort verbose
    0.1 TRUE TRUE  FALSE TRUE    2    TRUE

Absolute minimum support count: 48 

set item appearances ...[0 item(s)] done [0.00s].
set transactions ...[1298 item(s), 48744 transaction(s)] done [0.01s].
sorting and recoding items ... [159 item(s)] done [0.00s].
creating transaction tree ... done [0.01s].
checking subsets of size 1 done [0.00s].
writing ... [0 rule(s)] done [0.00s].
creating S4 object  ... done [0.00s].
```
below is my session information.
```{r}
> devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language en                          
 collate  Japanese_Japan.932          
 tz       Asia/Tokyo                  
 date     2017-10-15
...
> library('shinyjs')
> packageVersion('shinyjs')
[1] ‘0.9.1’
```

**Comment by daattali** [comment] 2017-10-15 19:18
@englianhu it's not clear to me that what you're showing is a shinyjs problem. If you believe there is a problem with shinyjs, please send a minimal reproducible example. (Your current code is neither minimal - because it contains several different packages and a lot of code that is unrelated - and also not reproducible because it sources other R scripts that are not given)

**Comment by daattali** [comment] 2019-02-19 18:07
@Ksyula thanks for the great bug report with reproducible example and details. This issue really should not be happening anymore for any package that is on CRAN, so I'm very confused, there's got to be something weird going on here with how `apriori` is printing the object. I'll take a look.

**Comment by daattali** [comment] 2019-02-19 18:27
@Ksyula after debugging this and looking into the `apriori()` source code, I was able to reduce the reproducibility to just:

```
library(arules)
library(shinyjs)
test <- as(list(supp = 0.01, conf = 0.8), "APparameter")
test
print(test)
```

Note that calling `test` in the console **does** work but explicitly calling out `print()` on it does not. This is because S4 obejcts (APparameter is an s4 object) should not be `print`ed, they need to use the `show()` function. I've filed a bug report with `arules` for, as this is entirely an issue on their end https://github.com/mhahsler/arules/issues/50
