### ISSUE TITLE
renderUI() fails with shinyjs 2.0 which works with shinyjs 1.0

### ISSUE THREAD

**Issue by iqbals** [daattali/shinyjs#227] opened 2020-12-29 19:45 UTC
I have an error:
```
Warning: Error in renderUI: attempt to apply non-function
  96: renderUI [/Users/sumaiya/Broad_Work/v2p/App/miscast07302020_replica/miscast07302020_r2/server.R#8281]
  95: func
  82: origRenderFunc
  81: output$msaResearchVSR
   1: shiny::runApp

```
thrown from following lines in the server.R

```
output$msaResearchVSR <- renderUI({
    gene_wise_info=read_delim(paste("gene_wise_info/",input$reportTgeneSelected,".txt",sep=''), "\t", escape_double = FALSE, trim_ws = TRUE)
    shinyjs::js$runMsa(containerId=msaContainerVSRId, aaInputId="aa_Selected", sequence=paste(gene_wise_info$`Amino Acid`, collapse=""))
  })
```
 
The code and my app runs perfectly with shinyjs 1.0, but when I installed shinyjs 2.0, I get this error.
Any help will be very much appreciated

**Comment by daattali** [comment] 2020-12-29 19:51
duplicate of #228

**Closed by daattali** 2020-12-29 19:51 UTC
