### ISSUE TITLE
info won't play nicely with updateInput

### ISSUE THREAD

**Issue by carlganz** [daattali/shinyjs#65] opened 2016-05-03 20:31 UTC
Hey Dean,

Thanks for the wonderful package. I have found that `updateSelectizeInput` behaves oddly when `shinyjs::info` is called in the same `observeEvent`. In the example below, change the value in the `selectizeInput` then press the button. The `selectizeInput` won't update even though the observeEvent changes it. 

```
library(shiny)
library(shinyjs)
runApp(list(ui= fluidPage(useShinyjs(),
  titlePanel("Test"),
  sidebarPanel(
    selectizeInput('test',label="Change me",choices=1:5),
    actionButton("btn","Press me")
  ),
  mainPanel(
    hidden(tags$div(h3("A button has been pressed"),id="testmessage"))
  )
),
server = function(session, input, output) {
  observeEvent(input$btn,{
    show("testmessage")
    Sys.sleep(2)
    info("Thanks for pressing. Selectize should go back to 1 now.")
    updateSelectizeInput(session,'test',selected=1)
    hide("testmessage")
  })
}))
```
If you comment out `info("Thanks for pressing. Selectize should go back to 1 now.")` everything works as expected. I don't know if this a problem on the `shiny` side or the `shinyjs` side or if I am misunderstanding how javascript works. 

Thanks!

**Comment by daattali** [comment] 2016-05-03 21:04
Thanks for the report.

FYI - you can use `shinyjs::delay()` instead of `Sys.sleep()`

It looks like this is a shiny problem, not a shinyjs problem. I might report it to RStudio later.  To confirm, here's a more minimal app that hits a few problems using pure Shiny

```
library(shiny)
runApp(list(ui = fluidPage(
  tags$script(
    "Shiny.addCustomMessageHandler('message', function(params) { alert(params); });
     Shiny.addCustomMessageHandler('hideit', function(params) { $('#hidden').toggle(); });"
  ),
  selectizeInput('test',label="Change me",choices=1:5),
  actionButton("btn","Press me"),
  div(id = "hidden", "hidden", style = "display: none;")
),
server = function(input, output, session) {
  observeEvent(input$btn,{
    session$sendCustomMessage('message', 'hello')
    session$sendCustomMessage('message', 'hello again')
    session$sendCustomMessage('hideit', '')
    updateSelectizeInput(session,'test',selected = 1)
  })
}))
```

And here's the equivalent with shinyjs (the exact same problems happen)

```
library(shiny)
runApp(list(ui = fluidPage(
  shinyjs::useShinyjs(),
  selectizeInput('test',label="Change me",choices=1:5),
  actionButton("btn","Press me"),
  div(id = "hidden", "hidden", style = "display: none;")
),
server = function(input, output, session) {
  observeEvent(input$btn,{
    shinyjs::info('hello')
    shinyjs::info('hello again')
    shinyjs::toggle('hidden')
    updateSelectizeInput(session,'test',selected = 1)
  })
}))
```

It does look like SHiny doesn't handle perfectly the case when multiple messages are being submitted to JS in a short amount of time

**Comment by daattali** [comment] 2016-05-03 23:06
Reported to shiny https://github.com/rstudio/shiny/issues/1181

**Comment by daattali** [comment] 2016-05-04 03:08
@carlganz are you on Windows? I am on Windows and I see this problem, but I just tested it on my RStudio server (running under Linux) and it works fine there , so I'm wondering if it's a Windows-only issue

**Comment by carlganz** [comment] 2016-05-04 04:49
Hey @daattali, I was running Windows when I had the problem. I can produce `sessionInfo()` tomorrow when I am back in front of my PC. Thanks for investigating this issue for me.

**Comment by daattali** [comment] 2016-05-04 04:54
If you have a different computer, I'd be interested to see if you can
reproduce the problem on a non Windows as well

---
http://deanattali.com

**Comment by carlganz** [comment] 2016-05-04 06:23
It works perfectly fine on my Mac. Appears to be a Windows problem

**Comment by daattali** [comment] 2016-05-04 06:39
Cool, thanks for verifying.

**Comment by carlganz** [comment] 2016-05-10 19:17
I stumbled upon this issue rstudio/DT#264 that you filed, and I am pretty sure it is the same problem as this issue.

**Comment by daattali** [comment] 2016-05-10 19:23
You're right, I forgot about that issue! Thanks for showing me, I'll add it to the shiny bug report

**Comment by daattali** [comment] 2016-07-21 21:26
@carlganz do you remember if you were seeing this issue in a real browser or was it happening only inside RStudio?  Can you try again now with the dev version of `shiny` and see if it works for you in a browser?  I just tried it and for me it's only broken within RStudio, which I'm ok with.......

**Comment by carlganz** [comment] 2016-07-21 21:49
Yeah, I was definitely seeing it in RStudio. Without using the dev version, I tried the example from above in Chrome and it ran fine.

**Comment by daattali** [comment] 2016-07-21 21:53
OK, I suppose it's up to the shiny team then, hopefully they'll look into why it's broken in RStudio https://github.com/rstudio/shiny/issues/1181

**Comment by daattali** [comment] 2016-08-09 19:18
@carlganz I'm going to close this issue because I think it is completely a shiny issue. And I don't think shiny devs will fix it, seeing as they closed the issue today and just assigned it a "low priority bug" label https://github.com/rstudio/shiny/issues/1181

**Closed by daattali** 2016-08-09 19:18 UTC
